//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanzFloor.Web.ws.filemanager {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Documento", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Documento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private System.Guid guidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreArchivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] MD5Field;
        
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BufferField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DanzFloor.Web.ws.filemanager.Carpeta CarpetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DanzFloor.Web.ws.filemanager.Servidor ServidorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DanzFloor.Web.ws.filemanager.TiposDocumento TipoDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid guid {
            get {
                return this.guidField;
            }
            set {
                if ((this.guidField.Equals(value) != true)) {
                    this.guidField = value;
                    this.RaisePropertyChanged("guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NombreArchivo {
            get {
                return this.NombreArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreArchivoField, value) != true)) {
                    this.NombreArchivoField = value;
                    this.RaisePropertyChanged("NombreArchivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] MD5 {
            get {
                return this.MD5Field;
            }
            set {
                if ((object.ReferenceEquals(this.MD5Field, value) != true)) {
                    this.MD5Field = value;
                    this.RaisePropertyChanged("MD5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] Buffer {
            get {
                return this.BufferField;
            }
            set {
                if ((object.ReferenceEquals(this.BufferField, value) != true)) {
                    this.BufferField = value;
                    this.RaisePropertyChanged("Buffer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public DanzFloor.Web.ws.filemanager.Carpeta Carpeta {
            get {
                return this.CarpetaField;
            }
            set {
                if ((object.ReferenceEquals(this.CarpetaField, value) != true)) {
                    this.CarpetaField = value;
                    this.RaisePropertyChanged("Carpeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public DanzFloor.Web.ws.filemanager.Servidor Servidor {
            get {
                return this.ServidorField;
            }
            set {
                if ((object.ReferenceEquals(this.ServidorField, value) != true)) {
                    this.ServidorField = value;
                    this.RaisePropertyChanged("Servidor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public DanzFloor.Web.ws.filemanager.TiposDocumento TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Carpeta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Carpeta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Servidor", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Servidor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarpetaAccesoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IP {
            get {
                return this.IPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPField, value) != true)) {
                    this.IPField = value;
                    this.RaisePropertyChanged("IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CarpetaAcceso {
            get {
                return this.CarpetaAccesoField;
            }
            set {
                if ((object.ReferenceEquals(this.CarpetaAccesoField, value) != true)) {
                    this.CarpetaAccesoField = value;
                    this.RaisePropertyChanged("CarpetaAcceso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TiposDocumento", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TiposDocumento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ws.filemanager.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name errorDescription from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddError", ReplyAction="*")]
        DanzFloor.Web.ws.filemanager.AddErrorResponse AddError(DanzFloor.Web.ws.filemanager.AddErrorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddError", ReplyAction="*")]
        System.Threading.Tasks.Task<DanzFloor.Web.ws.filemanager.AddErrorResponse> AddErrorAsync(DanzFloor.Web.ws.filemanager.AddErrorRequest request);
        
        // CODEGEN: Generating message contract since element name GetFileDocumentResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileDocument", ReplyAction="*")]
        DanzFloor.Web.ws.filemanager.GetFileDocumentResponse GetFileDocument(DanzFloor.Web.ws.filemanager.GetFileDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<DanzFloor.Web.ws.filemanager.GetFileDocumentResponse> GetFileDocumentAsync(DanzFloor.Web.ws.filemanager.GetFileDocumentRequest request);
        
        // CODEGEN: Generating message contract since element name GetFileResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFile", ReplyAction="*")]
        DanzFloor.Web.ws.filemanager.GetFileResponse GetFile(DanzFloor.Web.ws.filemanager.GetFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFile", ReplyAction="*")]
        System.Threading.Tasks.Task<DanzFloor.Web.ws.filemanager.GetFileResponse> GetFileAsync(DanzFloor.Web.ws.filemanager.GetFileRequest request);
        
        // CODEGEN: Generating message contract since element name sfilename from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileByName", ReplyAction="*")]
        DanzFloor.Web.ws.filemanager.GetFileByNameResponse GetFileByName(DanzFloor.Web.ws.filemanager.GetFileByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileByName", ReplyAction="*")]
        System.Threading.Tasks.Task<DanzFloor.Web.ws.filemanager.GetFileByNameResponse> GetFileByNameAsync(DanzFloor.Web.ws.filemanager.GetFileByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetFile", ReplyAction="*")]
        DanzFloor.Web.ws.filemanager.SetFileResponse SetFile(DanzFloor.Web.ws.filemanager.SetFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetFile", ReplyAction="*")]
        System.Threading.Tasks.Task<DanzFloor.Web.ws.filemanager.SetFileResponse> SetFileAsync(DanzFloor.Web.ws.filemanager.SetFileRequest request);
        
        // CODEGEN: Generating message contract since element name sfilename from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FileExists", ReplyAction="*")]
        DanzFloor.Web.ws.filemanager.FileExistsResponse FileExists(DanzFloor.Web.ws.filemanager.FileExistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FileExists", ReplyAction="*")]
        System.Threading.Tasks.Task<DanzFloor.Web.ws.filemanager.FileExistsResponse> FileExistsAsync(DanzFloor.Web.ws.filemanager.FileExistsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddErrorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddError", Namespace="http://tempuri.org/", Order=0)]
        public DanzFloor.Web.ws.filemanager.AddErrorRequestBody Body;
        
        public AddErrorRequest() {
        }
        
        public AddErrorRequest(DanzFloor.Web.ws.filemanager.AddErrorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddErrorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string errorDescription;
        
        public AddErrorRequestBody() {
        }
        
        public AddErrorRequestBody(string errorDescription) {
            this.errorDescription = errorDescription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddErrorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddErrorResponse", Namespace="http://tempuri.org/", Order=0)]
        public DanzFloor.Web.ws.filemanager.AddErrorResponseBody Body;
        
        public AddErrorResponse() {
        }
        
        public AddErrorResponse(DanzFloor.Web.ws.filemanager.AddErrorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddErrorResponseBody {
        
        public AddErrorResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileDocument", Namespace="http://tempuri.org/", Order=0)]
        public DanzFloor.Web.ws.filemanager.GetFileDocumentRequestBody Body;
        
        public GetFileDocumentRequest() {
        }
        
        public GetFileDocumentRequest(DanzFloor.Web.ws.filemanager.GetFileDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid guid;
        
        public GetFileDocumentRequestBody() {
        }
        
        public GetFileDocumentRequestBody(System.Guid guid) {
            this.guid = guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileDocumentResponse", Namespace="http://tempuri.org/", Order=0)]
        public DanzFloor.Web.ws.filemanager.GetFileDocumentResponseBody Body;
        
        public GetFileDocumentResponse() {
        }
        
        public GetFileDocumentResponse(DanzFloor.Web.ws.filemanager.GetFileDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DanzFloor.Web.ws.filemanager.Documento GetFileDocumentResult;
        
        public GetFileDocumentResponseBody() {
        }
        
        public GetFileDocumentResponseBody(DanzFloor.Web.ws.filemanager.Documento GetFileDocumentResult) {
            this.GetFileDocumentResult = GetFileDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFile", Namespace="http://tempuri.org/", Order=0)]
        public DanzFloor.Web.ws.filemanager.GetFileRequestBody Body;
        
        public GetFileRequest() {
        }
        
        public GetFileRequest(DanzFloor.Web.ws.filemanager.GetFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid guid;
        
        public GetFileRequestBody() {
        }
        
        public GetFileRequestBody(System.Guid guid) {
            this.guid = guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public DanzFloor.Web.ws.filemanager.GetFileResponseBody Body;
        
        public GetFileResponse() {
        }
        
        public GetFileResponse(DanzFloor.Web.ws.filemanager.GetFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetFileResult;
        
        public GetFileResponseBody() {
        }
        
        public GetFileResponseBody(byte[] GetFileResult) {
            this.GetFileResult = GetFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileByName", Namespace="http://tempuri.org/", Order=0)]
        public DanzFloor.Web.ws.filemanager.GetFileByNameRequestBody Body;
        
        public GetFileByNameRequest() {
        }
        
        public GetFileByNameRequest(DanzFloor.Web.ws.filemanager.GetFileByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sfilename;
        
        public GetFileByNameRequestBody() {
        }
        
        public GetFileByNameRequestBody(string sfilename) {
            this.sfilename = sfilename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public DanzFloor.Web.ws.filemanager.GetFileByNameResponseBody Body;
        
        public GetFileByNameResponse() {
        }
        
        public GetFileByNameResponse(DanzFloor.Web.ws.filemanager.GetFileByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetFileByNameResult;
        
        public GetFileByNameResponseBody() {
        }
        
        public GetFileByNameResponseBody(byte[] GetFileByNameResult) {
            this.GetFileByNameResult = GetFileByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetFile", Namespace="http://tempuri.org/", Order=0)]
        public DanzFloor.Web.ws.filemanager.SetFileRequestBody Body;
        
        public SetFileRequest() {
        }
        
        public SetFileRequest(DanzFloor.Web.ws.filemanager.SetFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] buffer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string filename;
        
        public SetFileRequestBody() {
        }
        
        public SetFileRequestBody(byte[] buffer, string filename) {
            this.buffer = buffer;
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public DanzFloor.Web.ws.filemanager.SetFileResponseBody Body;
        
        public SetFileResponse() {
        }
        
        public SetFileResponse(DanzFloor.Web.ws.filemanager.SetFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid SetFileResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool error;
        
        public SetFileResponseBody() {
        }
        
        public SetFileResponseBody(System.Guid SetFileResult, bool error) {
            this.SetFileResult = SetFileResult;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FileExistsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FileExists", Namespace="http://tempuri.org/", Order=0)]
        public DanzFloor.Web.ws.filemanager.FileExistsRequestBody Body;
        
        public FileExistsRequest() {
        }
        
        public FileExistsRequest(DanzFloor.Web.ws.filemanager.FileExistsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FileExistsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sfilename;
        
        public FileExistsRequestBody() {
        }
        
        public FileExistsRequestBody(string sfilename) {
            this.sfilename = sfilename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FileExistsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FileExistsResponse", Namespace="http://tempuri.org/", Order=0)]
        public DanzFloor.Web.ws.filemanager.FileExistsResponseBody Body;
        
        public FileExistsResponse() {
        }
        
        public FileExistsResponse(DanzFloor.Web.ws.filemanager.FileExistsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FileExistsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool FileExistsResult;
        
        public FileExistsResponseBody() {
        }
        
        public FileExistsResponseBody(bool FileExistsResult) {
            this.FileExistsResult = FileExistsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : DanzFloor.Web.ws.filemanager.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<DanzFloor.Web.ws.filemanager.Service1Soap>, DanzFloor.Web.ws.filemanager.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DanzFloor.Web.ws.filemanager.AddErrorResponse DanzFloor.Web.ws.filemanager.Service1Soap.AddError(DanzFloor.Web.ws.filemanager.AddErrorRequest request) {
            return base.Channel.AddError(request);
        }
        
        public void AddError(string errorDescription) {
            DanzFloor.Web.ws.filemanager.AddErrorRequest inValue = new DanzFloor.Web.ws.filemanager.AddErrorRequest();
            inValue.Body = new DanzFloor.Web.ws.filemanager.AddErrorRequestBody();
            inValue.Body.errorDescription = errorDescription;
            DanzFloor.Web.ws.filemanager.AddErrorResponse retVal = ((DanzFloor.Web.ws.filemanager.Service1Soap)(this)).AddError(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DanzFloor.Web.ws.filemanager.AddErrorResponse> DanzFloor.Web.ws.filemanager.Service1Soap.AddErrorAsync(DanzFloor.Web.ws.filemanager.AddErrorRequest request) {
            return base.Channel.AddErrorAsync(request);
        }
        
        public System.Threading.Tasks.Task<DanzFloor.Web.ws.filemanager.AddErrorResponse> AddErrorAsync(string errorDescription) {
            DanzFloor.Web.ws.filemanager.AddErrorRequest inValue = new DanzFloor.Web.ws.filemanager.AddErrorRequest();
            inValue.Body = new DanzFloor.Web.ws.filemanager.AddErrorRequestBody();
            inValue.Body.errorDescription = errorDescription;
            return ((DanzFloor.Web.ws.filemanager.Service1Soap)(this)).AddErrorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DanzFloor.Web.ws.filemanager.GetFileDocumentResponse DanzFloor.Web.ws.filemanager.Service1Soap.GetFileDocument(DanzFloor.Web.ws.filemanager.GetFileDocumentRequest request) {
            return base.Channel.GetFileDocument(request);
        }
        
        public DanzFloor.Web.ws.filemanager.Documento GetFileDocument(System.Guid guid) {
            DanzFloor.Web.ws.filemanager.GetFileDocumentRequest inValue = new DanzFloor.Web.ws.filemanager.GetFileDocumentRequest();
            inValue.Body = new DanzFloor.Web.ws.filemanager.GetFileDocumentRequestBody();
            inValue.Body.guid = guid;
            DanzFloor.Web.ws.filemanager.GetFileDocumentResponse retVal = ((DanzFloor.Web.ws.filemanager.Service1Soap)(this)).GetFileDocument(inValue);
            return retVal.Body.GetFileDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DanzFloor.Web.ws.filemanager.GetFileDocumentResponse> DanzFloor.Web.ws.filemanager.Service1Soap.GetFileDocumentAsync(DanzFloor.Web.ws.filemanager.GetFileDocumentRequest request) {
            return base.Channel.GetFileDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<DanzFloor.Web.ws.filemanager.GetFileDocumentResponse> GetFileDocumentAsync(System.Guid guid) {
            DanzFloor.Web.ws.filemanager.GetFileDocumentRequest inValue = new DanzFloor.Web.ws.filemanager.GetFileDocumentRequest();
            inValue.Body = new DanzFloor.Web.ws.filemanager.GetFileDocumentRequestBody();
            inValue.Body.guid = guid;
            return ((DanzFloor.Web.ws.filemanager.Service1Soap)(this)).GetFileDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DanzFloor.Web.ws.filemanager.GetFileResponse DanzFloor.Web.ws.filemanager.Service1Soap.GetFile(DanzFloor.Web.ws.filemanager.GetFileRequest request) {
            return base.Channel.GetFile(request);
        }
        
        public byte[] GetFile(System.Guid guid) {
            DanzFloor.Web.ws.filemanager.GetFileRequest inValue = new DanzFloor.Web.ws.filemanager.GetFileRequest();
            inValue.Body = new DanzFloor.Web.ws.filemanager.GetFileRequestBody();
            inValue.Body.guid = guid;
            DanzFloor.Web.ws.filemanager.GetFileResponse retVal = ((DanzFloor.Web.ws.filemanager.Service1Soap)(this)).GetFile(inValue);
            return retVal.Body.GetFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DanzFloor.Web.ws.filemanager.GetFileResponse> DanzFloor.Web.ws.filemanager.Service1Soap.GetFileAsync(DanzFloor.Web.ws.filemanager.GetFileRequest request) {
            return base.Channel.GetFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<DanzFloor.Web.ws.filemanager.GetFileResponse> GetFileAsync(System.Guid guid) {
            DanzFloor.Web.ws.filemanager.GetFileRequest inValue = new DanzFloor.Web.ws.filemanager.GetFileRequest();
            inValue.Body = new DanzFloor.Web.ws.filemanager.GetFileRequestBody();
            inValue.Body.guid = guid;
            return ((DanzFloor.Web.ws.filemanager.Service1Soap)(this)).GetFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DanzFloor.Web.ws.filemanager.GetFileByNameResponse DanzFloor.Web.ws.filemanager.Service1Soap.GetFileByName(DanzFloor.Web.ws.filemanager.GetFileByNameRequest request) {
            return base.Channel.GetFileByName(request);
        }
        
        public byte[] GetFileByName(string sfilename) {
            DanzFloor.Web.ws.filemanager.GetFileByNameRequest inValue = new DanzFloor.Web.ws.filemanager.GetFileByNameRequest();
            inValue.Body = new DanzFloor.Web.ws.filemanager.GetFileByNameRequestBody();
            inValue.Body.sfilename = sfilename;
            DanzFloor.Web.ws.filemanager.GetFileByNameResponse retVal = ((DanzFloor.Web.ws.filemanager.Service1Soap)(this)).GetFileByName(inValue);
            return retVal.Body.GetFileByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DanzFloor.Web.ws.filemanager.GetFileByNameResponse> DanzFloor.Web.ws.filemanager.Service1Soap.GetFileByNameAsync(DanzFloor.Web.ws.filemanager.GetFileByNameRequest request) {
            return base.Channel.GetFileByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<DanzFloor.Web.ws.filemanager.GetFileByNameResponse> GetFileByNameAsync(string sfilename) {
            DanzFloor.Web.ws.filemanager.GetFileByNameRequest inValue = new DanzFloor.Web.ws.filemanager.GetFileByNameRequest();
            inValue.Body = new DanzFloor.Web.ws.filemanager.GetFileByNameRequestBody();
            inValue.Body.sfilename = sfilename;
            return ((DanzFloor.Web.ws.filemanager.Service1Soap)(this)).GetFileByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DanzFloor.Web.ws.filemanager.SetFileResponse DanzFloor.Web.ws.filemanager.Service1Soap.SetFile(DanzFloor.Web.ws.filemanager.SetFileRequest request) {
            return base.Channel.SetFile(request);
        }
        
        public System.Guid SetFile(byte[] buffer, string filename, out bool error) {
            DanzFloor.Web.ws.filemanager.SetFileRequest inValue = new DanzFloor.Web.ws.filemanager.SetFileRequest();
            inValue.Body = new DanzFloor.Web.ws.filemanager.SetFileRequestBody();
            inValue.Body.buffer = buffer;
            inValue.Body.filename = filename;
            DanzFloor.Web.ws.filemanager.SetFileResponse retVal = ((DanzFloor.Web.ws.filemanager.Service1Soap)(this)).SetFile(inValue);
            error = retVal.Body.error;
            return retVal.Body.SetFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DanzFloor.Web.ws.filemanager.SetFileResponse> DanzFloor.Web.ws.filemanager.Service1Soap.SetFileAsync(DanzFloor.Web.ws.filemanager.SetFileRequest request) {
            return base.Channel.SetFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<DanzFloor.Web.ws.filemanager.SetFileResponse> SetFileAsync(byte[] buffer, string filename) {
            DanzFloor.Web.ws.filemanager.SetFileRequest inValue = new DanzFloor.Web.ws.filemanager.SetFileRequest();
            inValue.Body = new DanzFloor.Web.ws.filemanager.SetFileRequestBody();
            inValue.Body.buffer = buffer;
            inValue.Body.filename = filename;
            return ((DanzFloor.Web.ws.filemanager.Service1Soap)(this)).SetFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DanzFloor.Web.ws.filemanager.FileExistsResponse DanzFloor.Web.ws.filemanager.Service1Soap.FileExists(DanzFloor.Web.ws.filemanager.FileExistsRequest request) {
            return base.Channel.FileExists(request);
        }
        
        public bool FileExists(string sfilename) {
            DanzFloor.Web.ws.filemanager.FileExistsRequest inValue = new DanzFloor.Web.ws.filemanager.FileExistsRequest();
            inValue.Body = new DanzFloor.Web.ws.filemanager.FileExistsRequestBody();
            inValue.Body.sfilename = sfilename;
            DanzFloor.Web.ws.filemanager.FileExistsResponse retVal = ((DanzFloor.Web.ws.filemanager.Service1Soap)(this)).FileExists(inValue);
            return retVal.Body.FileExistsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DanzFloor.Web.ws.filemanager.FileExistsResponse> DanzFloor.Web.ws.filemanager.Service1Soap.FileExistsAsync(DanzFloor.Web.ws.filemanager.FileExistsRequest request) {
            return base.Channel.FileExistsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DanzFloor.Web.ws.filemanager.FileExistsResponse> FileExistsAsync(string sfilename) {
            DanzFloor.Web.ws.filemanager.FileExistsRequest inValue = new DanzFloor.Web.ws.filemanager.FileExistsRequest();
            inValue.Body = new DanzFloor.Web.ws.filemanager.FileExistsRequestBody();
            inValue.Body.sfilename = sfilename;
            return ((DanzFloor.Web.ws.filemanager.Service1Soap)(this)).FileExistsAsync(inValue);
        }
    }
}
