// <auto-generated />
namespace DanzFloor.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MuchosAMuchosBandaArtista : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MuchosAMuchosBandaArtista));
        
        string IMigrationMetadata.Id
        {
            get { return "201711232127535_Muchos-A-Muchos-Banda-Artista"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
